### ISSUE TITLE
Little Help Needed here in Canada

### ISSUE THREAD

**Issue by Tatt2edone** [mzst123/Xdrip-Lipo-Board#2]
I have ordered the boards from OSH Park, I am currently looking for all the parts needed, my question involves the micro switches, are they a must? I currently have an xDrip Wireless Bridge built, there are no switches, its always on. I get the on/off switch option, but what is the difference between xdrip circuit and xbridge circuit? 

I am sorry if this is a dumb question, just don't want to mess this up.

**Comment by mzst123** [comment]
Hello, switches are not a must, but I have them because if you choose to solder on the battery permanently, you have no way to reboot or turn off the device, for troubleshooting etc... 
If you don't want to use the switches, just bridge the contacts with a little wire and solder.
There are two circuits, wich vary only slightly. 
The original **xDrip** project used a circuit, wich was then further improved by John (jstevensog) and called **xBridge**.
He changed the [Wixel Program](https://github.com/jstevensog/wixel-sdk/tree/master/apps/xBridge2) to perform better and more efficient, and to show an approximate battery level value. You also don't have to compile the program each time you switch transmitters, because you can set the Transmitter ID from within the xDrip app. You can use this Wixel Program with both circuits, but the power saving features only work with the xBridge circuit.
Its up to you wich one you prefer, and with the switch you can easily test wich one works better for you. Another advantage is that the xBridge Wixel Program continues to be updated and improved to this day.
I personally use the xBridge circuit. 
As a side note, make sure you buy the exact micro-usb socket type as indicated, as there are many different versions and not all of them fit the layout perfectly.

Regards and good luck, if you have any questions ask away.

**Comment by Tatt2edone** [comment]
Thanks for the reply, I used the xDrip UK site to auto compile the wixel program for xDrip, but I think I will look into xBridge, 
Is this usb the correct one?

http://www.digikey.ca/scripts/DkSearch/dksus.dll?Detail&itemSeq=197088528&uq=635986860270805947

This company has all the parts listed and are in Canada so I don't have to worry about crazy exchange rates and long shipping times.

One last thing for now, I checked out the xBridge github, I am very new to this stuff, I am on my own building this stuff for my wife and just want to get it right for her. Can I just download the wixel file, reprogram my current xDrip box?

We are using the most current beta of xDrip, will it recognize the xBridge wixel program?

**Comment by mzst123** [comment]
Hi, unfortunately the link doesn't return a valid result. [This one](http://www.digikey.ca/product-detail/en/amphenol-fci/10118192-0001LF/609-4613-2-ND/2785387) should work, however it is not the one i used (cant find it on this site). The one i used has two little plastic legs that will fit the holes in the PCB, but for functionality it is not important, it just makes placing the part easier. If you are going to Reflow the board it doesn't matter, both will work fine.
About the xBridge, yes. Just download the .wxl file and load it on to the wixel. It should set itself up in a few minutes, watch the LEDs blinking, it is described in the PDF. You don't have to do anything. Just pair the device with the phone (I think HM-11 default pin is 000000 (six zeroes)) and xDrip should recognize the wixel just fine. Then enter the Transmitter ID. That's it. Regards

**Comment by Tatt2edone** [comment]
Hey, back again, I talked with digi-key about getting a jst-2 connector, apparently there are many variations in spacing for the pins. Do you remember what the spacing of the one you used? What type was it, right angle, flat (if there's such a thing) etc?

Thanks for your patience and help, I received shipping notice from OSH that the boards are on their way.

**Comment by mzst123** [comment]
Hey, [This is the one i used](https://www.sparkfun.com/products/8612) but i bought it from element14 as i am from europe. I bought all the other components from eBay with free shipping. Took over a month to arrive though. This connector is not strictly necessary as you can solder the battery directly on board if you can't source it. It is also quite expensive, that's why i left it optional. Digikey is very expensive on shipping. Regards
Edit: I forgot to add, they are the 2mm (header, smt) variant. Cheers

**Comment by mzst123** [comment]
I forgot to add, they are the 2mm (header, smt) variant. Cheers

**Comment by Tatt2edone** [comment]
Much appreciated! I will see what my area's supplier has. Cheers to you as well! DigiKey is only $8 shipping for all the parts I am ordering, everything needed in addition to what I have is there. I have 2 wixels, a bunch of hm-10 and a bunch of hm-11 on the way, I realize the hm-10 won't fit, but have them for old school xDrip builds in a pinch :)

**Comment by apabari** [comment]
Hello!  Tatt2edone, wondering -- do you have a parts list for the digikey order that you could post/share?  I'm also in Canada, and interested in ordering the components (and a board from OSHPark) -- just a little lost on the digikey website.

**Comment by apabari** [comment]
Just checking in!  Could anyone post the parts list for getting the components from digikey?

**Comment by mzst123** [comment]
Hey, its easier if you buy from eBay... lower prices because you can buy lower quantities... Didn't i send you a board some time ago? What happened?

**Comment by apabari** [comment]
I never received the board.  Lost our original e-mail thread so I didn't reach out again.  Do you have the tracking number? I'd love to try and find out what happened to it!

I ordered the components from e-bay and built one, but I'm pretty sure I ordered the wrong resistors and capacitors... it didn't work.  If you could point me at the product codes from digikey that would be great.  They do next day shipping and it's pretty inexpensive to order from them here in Toronto.

**Comment by mzst123** [comment]
So it was you. I wasn't sure. The board was returned to my address with a notice that it was delivered but not accepted. Im not sure if i still have the tracking number but it has probably expired anyway. Since you never reached out I forgot about it. I will look up the codes later today

**Comment by apabari** [comment]
That's really strange!  I am very disappointed to hear that.  If you could refund me the cost (less shipping, of course) I would really appreciate that as well.  Thanks for your help with finding the codes!

**Comment by mzst123** [comment]
Just sent you a refund! Here are some parts, if you need more help let me know:
[10KΩ resistor](http://www.digikey.pt/product-detail/en/yageo/RC1206FR-0710KL/311-10.0KFRCT-ND/731430)
[27kΩ Resistor](http://www.digikey.com/product-detail/en/yageo/RC1206FR-0727KL/311-27.0KFRCT-ND/731679)
[150Ω resistor](http://www.digikey.com/product-detail/en/yageo/RC1206JR-07150RL/311-150ERCT-ND/732170)
[10μf Capacitor](http://www.digikey.pt/product-detail/en/yageo/CC1206ZKY5V7BB106/311-1376-2-ND/2103114)
[LED](http://www.digikey.com/product-detail/en/kingbright/APT3216SURCK/754-1143-2-ND/1747542)

**Comment by apabari** [comment]
Thank you!  Just ordered the parts from Digi-Key.  Thanks so much for all of your continued help - hope this works out for me!
