### ISSUE TITLE
New to T1 & looking at getting set up

### ISSUE THREAD

**Issue by Deneil1983** [mzst123/Xdrip-Lipo-Board#3]
Morning I'm new to T1 Diabeties, my 5yr old daughter has been resently diagnosed. Be been trying to work out what's the best method for Xdrip while Mariella is at school. I've ordered the newest version of the PCB Xdrip board, wixel, HM11 but as far as anything else goes I haven't got a clue were or what there for. We're do I get the info to download the wixel? And could you post links were to get the rest of the components that I would need to get. I'm in the UK so anywere UK or Europe based would be a help xxx

**Comment by runeron** [comment]
Hello. I would suggest you read the following:
- [Nightscout](http://www.nightscout.info/)
- [xDrip](http://stephenblackwasalreadytaken.github.io/xDrip/)

Regarding the PCB blueprints posted here, they are for creating an additional/alternative Dexcom receiver. All components are listed on this site as well (and also the wiring diagram, for your question regarding the other components). It is marked on the PCB where each component goes. Personally I have used the following sites for ordering: eBay, SparkFun, HobbyTronics

NOTE: xBridge and xDrip are essentialy the same, but xBridge circuit has some additional functionality (at least that is how I understand it). Some of the "additional" components are only required if you use the xBridge setting (?).

My reasons for creating this board (still waiting for components):
- Monitor our 3 yr old (T1 for 6 months) even when he's in kindergarden/visiting others
- Use smartphones instead of the Dexcom receiver
- Uses "better" algorithm for calculating sender measurements, compared to the outdated Dexcom EU software

I would also sugges you check out the site listed below, which has instructions for creating a receiver to upload data to the "cloud" without need for an android phone:
- [Parakeet](http://jamorham.github.io/)

Best of luck!

**Comment by mzst123** [comment]
@runeron Yes that is exactly how it works. The only additional components the xBridge needs are two resistors to estimate battery level.

@Deneil1983 I have sourced almost all components from eBay, as the shipping is free (it takes a month to arrive from China or HongKong though). For example, for the LED, just go to `ebay.com` and enter `1206 Red LED`. Then you sort by `Price + Shipping: lowest first`and click on only show `Buy it now` results. Now scroll down a little until you find one result that you want, for example i got [this one](http://www.ebay.com/itm/10-x-1206-RED-Super-Bright-LED-Chip-SMD-SMT-Bulb-Lamp-Light-High-Brightness-RoHs-/191231419928?hash=item2c8647e618:g:O3sAAOSw9N1Vo3OF&vxp=mtr).
For $0.80 you get 10 Leds shipped to your house, no additional charges. Quite Cheap considering that on most other electronic websites you have to pay over 5€ in shipping. Now do the same process for all the other components. Here are some example links but consider that the prices change daily and shipping depends on where you are located (I live in Portugal). If you don't want to wait that long then order from a local supplier, for the UK i think Farnell/Element14 is good but expensive.
- [Resistors](http://www.ebay.com/itm/100pcs-1-4W-watt-1206-SMT-SMD-Chip-Resistor-from-0-ohm-to-10M-ohm-1-/252380762812?var=&hash=item3ac310d2bc:m:msXv_-i2Opl1RPDANdY3cMw)
- [Capacitors](http://www.ebay.com/itm/12pcs-1206-smd-tantalum-capacitor-16v-10uf-106-10-3216-a-type-ic-diy-develop-d1-/331840663464?hash=item4d433eafa8:g:MpYAAOSwubRXFXfc)
- [Micro Switch](http://www.ebay.com/itm/20-pcs-MSK-12C02-Mini-SPDT-1P2T-Slide-Switch-On-Off-SMD-7-Pin-For-MP3-MP4-/161857451517?hash=item25af74b5fd:g:e1IAAOSwl9BWHbT4)
- [Red Led](http://www.ebay.com/itm/10-x-1206-RED-Super-Bright-LED-Chip-SMD-SMT-Bulb-Lamp-Light-High-Brightness-RoHs-/191231419928?hash=item2c8647e618:g:O3sAAOSw9N1Vo3OF&vxp=mtr)
- [micro usb socket](http://www.ebay.com/itm/2015-New-10Pcs-Micro-USB-B-Female-5Pin-SMT-Socket-Connector-Hot-Sale-MO-/401091696043?hash=item5d62ed95ab:g:R2kAAOSwDNdVpfv5)
- [Max1811](http://www.ebay.com/itm/1PCS-USB-LI-CHARGER-IC-MAXIM-SOP-8-MAX1811ESA-MAX1811ESA-MAX1811ESA-T-/272041007390?hash=item3f56e8591e:g:rx0AAOSwAYtWPgb~)
- [LiPo battery](http://www.ebay.com/itm/3-7V-850mAh-Lipo-Polymer-li-ion-Battery-703040-for-cell-phone-Camera-DVD-GPS-PAD-/111909510772?hash=item1a0e539e74:g:FAoAAOSwFNZWxojb)

For the Wixel software i recommend [xBridge](https://github.com/jstevensog/wixel-sdk/tree/master/apps/xBridge2) from [John](https://github.com/jstevensog). Just download the .wxl file and load it to the wixel. There are many advantages of xBridge, for example you don't have to re-compile the program to change transmitters because you can set it inside the xDrip app. Regards

**Comment by Deneil1983** [comment]
Thank you for all your help, I think I've managed to get everything. Could you just double check these links to make sure there all correct before I go and buy them please?

https://www.ebay.co.uk/ulk/itm/121966808792 

https://www.ebay.co.uk/ulk/itm/391293464671 

https://www.ebay.co.uk/ulk/itm/361517418457 

https://www.ebay.co.uk/ulk/itm/321604978839 

https://www.ebay.co.uk/ulk/itm/261474884369 

https://www.ebay.co.uk/ulk/itm/191794514614 

https://www.ebay.co.uk/ulk/itm/151637924468

**Comment by mzst123** [comment]
Yes that looks good. Let me know when you finish it. Cheers
